# for OpenMined/Grid 
# https://github.com/OpenMined/Grid
#
# docker build -t grid .
# 
# TODO:
# should change to nvidia GPU images later (if pytoruch for GPU is required)
#

FROM ubuntu:16.04

# python3-pip, not python3-pip3
# To be comfirm:
# since miniconda is installed, maybe I don't need std python3 and python3-pip?
RUN apt-get update && \
    apt-get install -y \
    build-essential automake pkg-config libtool libffi-dev libgmp-dev \
    curl \
    git \
    bzip2 \
    libssl-dev && \
    # miniconda version of python and pip will be used instead
    # Clean up!    
    rm -rf /var/lib/apt/lists/*

# the go-ipfs version seems like amd specific?
RUN curl -O https://dist.ipfs.io/go-ipfs/v0.4.13/go-ipfs_v0.4.13_linux-amd64.tar.gz && \
    tar xvfz go-ipfs_v0.4.13_linux-amd64.tar.gz && \
    cd go-ipfs && \
    ./install.sh && \
    # clean up!
    rm -f ~/go-ipfs_v0.4.13_linux-amd64.tar.gz

# miniconda slient install
# ref: https://conda.io/docs/user-guide/install/macos.html#install-macos-silent
RUN cd ~/ && curl -O https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    bash ./Miniconda3-latest-Linux-x86_64.sh -b -p /miniconda && \
    export PATH="/miniconda/bin:$PATH" && \
    conda install --yes pytorch-cpu -c pytorch && \
    cd ~/ && \
    git clone https://github.com/OpenMined/Grid.git && \
    cd ~/Grid && \
    python setup.py install && \
    # clean up
    rm -f ~/Miniconda3-latest-Linux-x86_64.sh

WORKDIR ~/Grid
CMD export PATH="/miniconda/bin:$PATH" && \
    mkdir ~/.openmined && \
    echo '{"email": "someone@somewhere.com", "name": "someone"}' > ~/.openmined/whoami.json && \
    cd ~/Grid && \
    bash ./bin/start_worker

# {"email": "someone@somewhere.com", "name": "someone"}